apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftps
  name: ftps
spec:
  ports:
  - name: data
    port: 20
    targetPort: 20
  - name: ftps
    port: 21
    protocol: TCP
    targetPort: 21
  selector:
    app: ftps
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ftps
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ftps
    spec:
      containers:
      - image: service_ftps
        imagePullPolicy: Never
        name: ftps
        ports:
        - containerPort: 21
        - containerPort: 30021
