apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: telegraf
  name: telegraf
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegraf
  template:
    metadata:
      labels:
        app: telegraf
    spec:
      volumes:
        - name: docker-sock
          hostPath:
            path: /var/run/docker.sock
            type: Socket
      containers:
      - image: service_telegraf
        imagePullPolicy: Never
        name: telegraf
        volumeMounts:
          - name: docker-sock
            mountPath: /var/run/docker.sock
