apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  ports:
  - name: wordpress
    port: 5050
    protocol: TCP
    targetPort: 5050
  selector:
    app: wordpress
  type: LoadBalancer
  loadBalancerIP: 192.168.99.103
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: wordpress
    spec:
      containers:
      - image: service_wordpress
        env:
        - name: WORDPRESS_HOME
          value: 192.168.99.101:5050
        imagePullPolicy: Never
        name: wordpress
        ports:
        - containerPort: 5050  
