FLUSH PRIVILEGES;

CREATE DATABASE wordpress;

CREATE USER 'user'@'0.0.0.0' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON *.* TO 'user'@'0.0.0.0';

CREATE USER 'user'@'%' IDENTIFIED BY '';
GRANT ALL PRIVILEGES ON *.* TO 'user'@'%';

FLUSH PRIVILEGES;
