apiVersion: 1

datasources:
- name: "Telegraf database"
  orgId: 1
  type: influxdb
  access: proxy
  url: http://influxdb:8086
  database: telegraf
  isDefault: false
  version: 1
  editable: false
  basicAuth: true
  basicAuthUser: user
  basicAuthPassword: password